spring:
  application:
    name: json-api
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: create-drop
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${password}
    username: ${username}
    url: jdbc:postgresql://localhost:5432/is_project?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  error:
    whitelabel:
      enabled: 'false'
    path: /error
