spring:
  application:
    name: rates-collector
  jpa:
    properties:
      hibernate:
        default-schema: 'app_schema'
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/is_project?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  error:
    whitelabel:
      enabled: 'false'
    path: /error
